language: scala
scala:
  - 2.10.0
jdk:
  #the scala compiler has problems with jdk7 intermittenly
  - openjdk6
script:
  - "echo '-------------------------------------------------'"
  - "echo $TRAVIS_SCALA_VERSION"
  - "sbt -Duser.name=$USER.$RANDOM ++$TRAVIS_SCALA_VERSION assembly"
  - "scripts/test_tutorials.sh"

